name: topic-modelling
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h2082a12_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h753d554_5
  - aws-c-cal=0.9.8=hca30140_0
  - aws-c-common=0.12.5=hc919400_1
  - aws-c-compression=0.3.1=h61d5560_8
  - aws-c-event-stream=0.5.6=hada8b3e_4
  - aws-c-http=0.10.7=h241dc44_1
  - aws-c-io=0.23.2=hcea795d_2
  - aws-c-mqtt=0.13.3=hf26a141_8
  - aws-c-s3=0.8.6=h1e3b5a0_7
  - aws-c-sdkutils=0.2.4=h61d5560_3
  - aws-checksums=0.2.7=h61d5560_4
  - aws-crt-cpp=0.35.0=h44e95eb_2
  - aws-sdk-cpp=1.11.606=hf3ce6b4_6
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bertopic=0.17.3=pyhe01879c_0
  - brotli-python=1.2.0=py313h79bbab8_0
  - bs4=4.14.2=hd8ed1ab_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313h224173a_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - datasets=4.4.1=pyhcf101f3_0
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - frozenlist=1.7.0=py313hf28abc0_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py313hc1c22ca_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hdbscan=0.8.39=py313hc577518_1
  - hf-xet=1.2.0=py310h6ce4931_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=22.0.0=h4f7d3e6_3_cpu
  - libarrow-acero=22.0.0=hc317990_3_cpu
  - libarrow-compute=22.0.0=h75845d1_3_cpu
  - libarrow-dataset=22.0.0=hc317990_3_cpu
  - libarrow-substrait=22.0.0=h144af7f_3_cpu
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=22.0.0=h0ac143b_3_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.8.0=cpu_generic_hf67e7d3_2
  - libutf8proc=2.11.0=hc25f550_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_2
  - llvmlite=0.45.1=py313he297ed2_0
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py313h7d74516_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py313h6347b5a_0
  - multiprocess=0.70.18=py313h9734d34_2
  - narwhals=2.11.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h248ca61_1
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.62.1=py313h936dde2_0
  - numpy=2.3.4=py313h9771d21_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - optree=0.17.0=py313ha61f8ec_2
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h7d16b84_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py313h54da0cd_0
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py313ha9b7d5b_0
  - psutil=7.1.3=py313h9734d34_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py313h39782a4_0
  - pyarrow-core=22.0.0=py313hb9a0e51_0_cpu
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.9=hfc2f54d_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_101
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py313hee11f83_1
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h7d74516_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - regex=2025.11.3=py313h6535dbc_1
  - safetensors=0.6.2=py313h0b74987_2
  - scikit-learn=1.7.2=py313h6eea1c5_0
  - scipy=1.16.3=py313h0d10b07_0
  - sentence-transformers=5.1.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h66ce52b_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tokenizers=0.22.1=py313h4bd1e59_1
  - tornado=6.5.2=py313h6535dbc_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.57.1=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.9.post2=py313h8f79df9_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xxhash=0.8.3=haa4e116_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py313h7d74516_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py313h9734d34_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - charset-normalizer==2.0.12
      - classla==2.2.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.60.1
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - matplotlib==3.10.7
      - obeliks==1.1.6
      - protobuf==4.21.2
      - pyparsing==3.2.5
      - reldi-tokeniser==1.0.3
      - requests==2.28.0
      - sympy==1.13.1
      - torch==2.6.0
      - urllib3==1.26.20
      - wordcloud==1.9.4
prefix: /opt/anaconda3/envs/topic-modelling
