name: topic-modelling
channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel

  # python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - wordcloud

  # topic modelling (conda)
  - umap-learn
  - hdbscan
  - datasets
  - transformers
  - huggingface_hub

  # other
  - beautifulsoup4
  - requests
  - pyyaml

  - pip:
      - bertopic
      - sentence-transformers
      - classla
      - obeliks
      - reldi-tokeniser