name: topic-modelling
channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel

  # python
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - wordcloud

  # topic modelling
  - bertopic
  - sentence-transformers
  - umap-learn
  - hdbscan
  - datasets
  - transformers
  - huggingface_hub

  # sl lang / NLP
  - classla
  - obeliks
  - reldi-tokeniser

  # other
  - beautifulsoup4
  - requests
  - pyyaml
